spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  mvc:
    hiddenmethod:
      filter:
         enabled: true
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
  profiles:
    active: local
